### ISSUE TITLE
AutoHide(false) : doesn't work

### ISSUE THREAD

**Issue by minikin** [wxxsw/GSMessages#1]
```
override func viewDidLoad() {
  super.viewDidLoad()

  GSMessage.warningBackgroundColor = UIColor(hue:0.72, saturation:0.16, brightness:0.37, alpha:1)
  GSMessageOption.AutoHide(false)

  NSNotificationCenter.defaultCenter().addObserver(self, selector: "showInternetConnectionError", name:UnrealityNoInternetConnection, object: nil)
}
```

  func showInternetConnectionError(){
    self.showMessage("The Internet connection appears to be offline.", type: .Warning, options: nil)
  }
# 

.AutoHide(false)  doesn't work for me. What did I miss?
Thanks.

**Comment by wxxsw** [comment]
Try this:

```
self.showMessage("The Internet connection appears to be offline.", type: .Warning, options: [.AutoHide(false)])
```

  And remove ~~GSMessageOption.AutoHide(false)~~ 

# 

Use "GSMessageOption.AutoHide (false)" does not change the default behavior.
I will modify the README to avoid similar misleading, Thank you!
