### ISSUE TITLE
UITableViewController

### ISSUE THREAD

**Issue by eirikmadland** [wxxsw/GSMessages#2]
Hi.

I am using GSMessages in a lot of my projects and I really appriciate your work.

In one of my projects I noticed that if I create a GSMessage in a table view (after some debugging) the height variable is 20px more if I use it in a UITableView compared by another view.
If I choose to use the position .Bottom it actually shows the message out of sight.

Is it possible to fix that?

Regards
Eirik

**Comment by wxxsw** [comment]
This 10 days in my vacation, I'm sorry to reply you so late.

But, I don't know "if I use it in a UITableView compared by another view."is what meaning, please detailed description，thank you.

**Comment by eirikmadland** [comment]
If I use it in a UIViewController it works, but not in a UITableViewController.

**Comment by wxxsw** [comment]
Fixed in fbcc49f785d577d0e34ec93d70ad779f7d71bbb0.

**Comment by seyfeddin** [comment]
Awesome library!

I have a similar problem. when presented from UITableViewController, message is presented over the navigation bar.

![simulator screen shot 7 jun 2017 18 42 26](https://user-images.githubusercontent.com/180363/26887616-1f8f0eee-4bb1-11e7-9403-82d609a42092.png)

**Comment by wxxsw** [comment]
@seyfeddin Thanks for your feedback, I will fix it at this weekend 😉

**Comment by wxxsw** [comment]
@seyfeddin I should have completely fixed the problem in the new tag [1.3.5](https://github.com/wxxsw/GSMessages/tree/1.3.5), I also added the relevant demo to the example project, good luck.

The only thing to note is that when used in `UITableViewController`, you need to call `hideMessage()` in `viewWillDisappear` or `viewDidDisappear`, if not may cause the view controller to defer release.

**Comment by seyfeddin** [comment]
Thank you very much!
