### ISSUE TITLE
upgrade to swift 4

### ISSUE THREAD

**Issue by alexodus** [wxxsw/GSMessages#23]
Please upgrade to swift 4

**Comment by wxxsw** [comment]
I will be upgrading on this weekends.

**Comment by mrsnax** [comment]
I've 1.4.0

But error when running : 
**Type 'NSAttributedStringKey' (aka 'NSString') has no member 'font'**

**Comment by wxxsw** [comment]
@mrsnax Please use version `1.4.0` . https://cocoapods.org/pods/GSMessages

**Comment by mrsnax** [comment]
@wxxsw still error encountered :(

**Comment by wxxsw** [comment]
@mrsnax 

I created a new Swift 4 project and did not error encountered.

If you are Swift 3 project, run `pod install` will generate the corresponding Swift 3 Pod configuration, this can be solved:

```ruby
target 'YourTarget' do
  use_frameworks!

  pod 'GSMessages'
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == 'GSMessages'
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '4.0'
        end
      end
    end
  end

end
```
> https://github.com/CocoaPods/CocoaPods/issues/6791

If there are still errors, please reply.

**Comment by vitalii-tym** [comment]
~~@wxxsw CocoaPods have a solution already. This post install code won't be needed any more if you add this rule in podspec:
`spec.xcconfig = { 'SWIFT_VERSION' => '4.0' }`~~
more info here: https://github.com/CocoaPods/CocoaPods/issues/6791#issuecomment-333409224
UPD: Sorry, I was reading it too fast. I realize now it is still under discussion and not yet implemented in CocoaPods.
