### ISSUE TITLE
Position margin

### ISSUE THREAD

**Issue by rserentill** [wxxsw/GSMessages#24]
Thanks for this awesome tool!
Now, more than an issue, this would be kind of a suggestion.

It would be great if we could specify a top, right, left and/or bottom margin to the message view, because in my case, I have a view on the top of the screen.
I have also a view on background so I could use the `view.showMessage(...)` method, but the problem is that this view lays behind the top view, not below, so the message would appear on the absolute top of screen, not below the top view.

Thanks!

**Comment by rserentill** [comment]
Oh! I forgot to say that it would also be great if we could specify the text padding, but not only the left padding, because I'd like to put the text more at the bottom of the view, not vertically centered :)

**Comment by wxxsw** [comment]
I think this is a good suggestion!

My current idea is to add an option:

```swift
.margin(UIEdgeInsets) // If, for example, from the top show, setting the bottom margin may be meaningless
```

Also change the type of textAlignment option and remove textPadding option:

```swift
enum TextAlignment {
  case topLeft(topPadding: CGFloat, leftPadding: CGFloat)
  case topCenter(topPadding: CGFloat)
  case topRight(topPadding: CGFloat, rightPadding: CGFloat)
  case left(leftPadding: CGFloat)
  case center
  case right(rightPadding: CGFloat)
  case bottomLeft(bottomPadding: CGFloat, leftPadding: CGFloat)
  case bottomCenter(bottomPadding: CGFloat)
  case bottomRight(bottomPadding: CGFloat, rightPadding: CGFloat)
}

.textAlignment(TextAlignment)
```

I may have done this weekend or next weekend.

**Comment by wxxsw** [comment]
But for `margin`, there will be subtle differences in behavior.

E.g:

`viewController.showMessage...` will consider the navigation bar and the bottom area, so `margin` is set to increase the height.

And `view.showMessage...` is to set margin between the view.

**Comment by rserentill** [comment]
This sounds so cool!
So you think (in the margin case) there is no way to increase the x/y offset instead of the view's height? I think this would be the desired behavior, because there's already the `.height(Double)`option.

Thanks for your super fast reply and have a nice week!

**Comment by wxxsw** [comment]
My English is not good, I mean through the UIViewController call showMessage (`viewController.showMessage...`), will increase the height of the highlighted part of the screenshot.

<img width="336" alt="wx20171010-182001 2x" src="https://user-images.githubusercontent.com/921863/31381639-b3c6c6cc-ade7-11e7-87a9-09aadc770b39.png">
<img width="347" alt="wx20171010-182019 2x" src="https://user-images.githubusercontent.com/921863/31381641-b50d000a-ade7-11e7-88bb-c8195a7427c1.png">

It is x / y offset when using `view.showMessage ...`.
<img width="398" alt="wx20171010-182615 2x" src="https://user-images.githubusercontent.com/921863/31381923-87814866-ade8-11e7-85b5-caae33fc5d39.png">

**Comment by rserentill** [comment]
Oh! sorry, I understand what you mean now. This seems like the perfect solution for me :)

Thanks!

**Comment by wxxsw** [comment]
### API Changes:
-  Add `.margin(UIEdgeInsets)`
- Add `.cornerRadius(CGFloat)`
- Change `.textPadding(CGFloat)` to `.padding(UIEdgeInsets)`, the reason for not being removed is to limit the minimum distance of the text and the edge when the text is many or more lines.
- Change `.textAlignment(NSTextAlignment)` to `.textAlignment(GSMessageTextAlignment)` 
```swift 
public enum GSMessageTextAlignment {
    case topLeft
    case topCenter
    case topRight
    case left
    case center
    case right
    case bottomLeft
    case bottomCenter
    case bottomRight
}
```

### Demos

```swift
someView.showMessage("Margin", type: .success, options: [
    .margin(.init(top: 20, left: 20, bottom: 0, right: 20)),
    .cornerRadius(5)
])
```
<img width="312" alt="wx20171022-161022 2x" src="https://user-images.githubusercontent.com/921863/31859840-8e890cfc-b743-11e7-88de-13073c3255e6.png">

```swift
showMessage("Padding,Padding,Padding,Padding,Padding,Padding", type: .success, options: [
    .padding(.init(top: 10, left: 50, bottom: 10, right: 0))
])
```
<img width="313" alt="wx20171022-161217 2x" src="https://user-images.githubusercontent.com/921863/31859850-cd3c1476-b743-11e7-9f95-0f7607f6d60b.png">

```swift
showMessage("Rounded Corners", type: .success, options: [
    .cornerRadius(10),
    .margin(.init(top: 0, left: 10, bottom: 0, right: 10))
])
```
<img width="314" alt="wx20171022-161309 2x" src="https://user-images.githubusercontent.com/921863/31859861-eb1ecb50-b743-11e7-9d0b-b1bb60df9b9f.png">

```swift
showMessage("BottomRight", type: .success, options: [
    .textAlignment(.bottomRight),
    .padding(.init(top: 10, left: 30, bottom: 10, right: 30)),
    .height(60)
])
```
<img width="311" alt="wx20171022-161458 2x" src="https://user-images.githubusercontent.com/921863/31859871-28cea466-b744-11e7-8ac3-f4772b1a80f6.png">

**Comment by rserentill** [comment]
This is great, thank you!
