### ISSUE TITLE
Type 'NSAttributedStringKey' (aka 'NSString') has no member 'font' 

### ISSUE THREAD

**Issue by sirvon** [wxxsw/GSMessages#28]
Been getting this error since installing the pod.

```swift
Type 'NSAttributedStringKey' (aka 'NSString') has no member 'font' 
```

I'm using the latest xcode 9.2 beta and the latest swift 4.0.3
I checked build settings and my target is using swift 4.

From my research, NSAttributedStringKey just got a member "font" in swift 4.

What else may be going on?

**Comment by wxxsw** [comment]
If you are using cocoapods, you can check the build settings for GSMessages in the Pods project is using Swift 4. If not, this can be solved:

```swift
# Podfile

target 'YourTarget' do
  use_frameworks!

  pod 'GSMessages'
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == 'GSMessages'
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '4.0'
        end
      end
    end
  end

end
```
