### ISSUE TITLE
Type 'String' has no member 'font'

### ISSUE THREAD

**Issue by MarsXan** [wxxsw/GSMessages#31]
I got error in this part 
I'm using Xcode 9 with swift 4

```
let attributedText = NSAttributedString(
            string: text,
            attributes: [
                .font: GSMessage.font,
                .foregroundColor: UIColor.white,
                .paragraphStyle: NSParagraphStyle()
            ]
        )
```

**Comment by wxxsw** [comment]
I run this code in the demo did not find errors, can provide more information?

**Comment by MarsXan** [comment]
when I want to build my project with Xcode 9 and swift I get this error


<img width="920" alt="screen shot 2018-01-13 at 6 41 12 pm" src="https://user-images.githubusercontent.com/20490539/34907299-9aa52e14-f891-11e7-9f83-ad0612e66d24.png">
<img width="534" alt="screen shot 2018-01-13 at 6 41 31 pm" src="https://user-images.githubusercontent.com/20490539/34907300-9ac8dc6a-f891-11e7-8390-df7d485f5844.png">

**Comment by wxxsw** [comment]
Please check the Swift version of GSMessage in Pods.

**Comment by MarsXan** [comment]
I am using your library with xode8.2 and swift 3 with Carthage it works fine 
but I get this error in the last version "1.5.1" with cocoaPod

**Comment by wxxsw** [comment]
In Xcode9 Swift4 project to check this configuration:
![1515857228501](https://user-images.githubusercontent.com/921863/34907444-650beb8a-f8b9-11e7-81e5-3b092d3e1ecd.jpg)

Is Swift4?

**Comment by MarsXan** [comment]
Thanks, this solved My Problem. you can close this 👍
