### ISSUE TITLE
Not working correctly when using on presentingViewController

### ISSUE THREAD

**Issue by leonardodgl** [wxxsw/GSMessages#34]
Hi there!

I'm having an issue when I'm trying to display a message on the presentingViewController, the issue is that the height of the alert is the size of the navigation bar instead of the navigation bar height + additional height.

Do you know how to solve this?

**Comment by wxxsw** [comment]
Maybe you can set `margin`(top) to height of navigation bar, or set `height` and `padding`(top).

**Comment by leonardodgl** [comment]
Yeah, I can, but the thing is that if I show a message as self.showMessage it shows the banner with the expected height while using presentingViewController doesn't.

**Comment by wxxsw** [comment]
Is presentingViewController a UINavigationController or is contained in a UINavigationController?

**Comment by leonardodgl** [comment]
Yes, the presentingViewController is contained inside a UINavigationController

**Comment by wxxsw** [comment]
I found that presentingViewController does not return the same ViewController that called present as expected, it actually returns the top-most controller other than presentedViewController, such as UINavigationController.

So the correct call may become `(vc?.presentingViewController as? UINavigationController)?.viewControllers.first?.showMessage("...", type: .success)`

But this method is not only ugly but also fragile, i think it would be better to call in a custom callback:

```
let vc = ViewController()
vc.successCallback = { [unowned self] in
    self.showMessage("...", type: .success)
}
self.present(vc, animated: true, completion: nil)
```
