### ISSUE TITLE
Notification appears over main view but under another

### ISSUE THREAD

**Issue by ajRiverav** [wxxsw/GSMessages#40]
![image](https://user-images.githubusercontent.com/22076301/54851060-34371380-4cbf-11e9-89de-69508b9827e8.png)

How can I make sure the message shows up on top of all views in a view controller?

**Comment by wxxsw** [comment]
You can try to display the message on window. refer to: GSMessages/GSMessagesExample/GSMessagesExample/ViewController.swift - (tapWindow:)

**Comment by ajRiverav** [comment]
WIll try.
