### ISSUE TITLE
How do I get it to show over the navigation bar?

### ISSUE THREAD

**Issue by martinliu0** [wxxsw/GSMessages#7]
as title

**Comment by wxxsw** [comment]
Not support, may be you want: 
https://github.com/cezarywojcik/CWStatusBarNotification
https://github.com/cruffenach/CRToast

**Comment by martinliu0** [comment]
Actually I used a `UIWindow` (`message` was a `UIView` in the original version) and adjusted the `y` position and now it's doing what I wanted, 谢了!

**Comment by wxxsw** [comment]
Good job, 不客气 :)
