### ISSUE TITLE
About orientation

### ISSUE THREAD

**Issue by leandrodestro** [wxxsw/GSMessages#8]
I've noticed something I wouldn't call a issue, but a possible improvement:

After a message is displayed, if the user changes his iPhone orientation the displayed message is not being "resized and replaced" to fit to device's new orientation. Do you think it's something you'll be working on in the future? Maybe, if you won't, I could study your code and try to create this improvement, after I finish my current project (which's deadline is very soon)

**Comment by wxxsw** [comment]
Very thank you put forward this worthy of improvement, I ignored the problem, I am very happy to modify and improve it, thank you again for you.

After modification, I will reply to you.

**Comment by wxxsw** [comment]
I have improved this problem at https://github.com/wxxsw/GSMessages/commit/ddf8930ca6556e65a38969060370dea5909fb7de

**Comment by wxxsw** [comment]
You can use the latest release 1.2.2

**Comment by leandrodestro** [comment]
That was a great timing from you! Thanks for your attention! :+1:
